services:
  postgres:
    image: postgres:16-alpine
    container_name: crop_disease_db
    env_file: .env
    ports:
      - "${POSTGRES_PORT:-5434}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
